#!/bin/bash
CURRENT=$(df / | grep / | awk '{ print $5,$6}' | sed 's/%//g')
CRITICAL=90
WARNING=80
if [ "`echo $CURRENT| awk '{print $1}'`" -gt "$CRITICAL" ] ; then
echo 'CRITICAL!!! Disk Space Alert' 
echo 'hello{\"MessageType\": \"DiskSpace\",   \"Level\": \"Critical\",\"Time\": \"`date`\",\"Message\": \"CRITICAL!!! Disk Space Alert\"}'
elif [ "`echo $CURRENT| awk '{print $1}'`" -gt "$WARNING" -a "`echo $CURRENT| awk '{print $1}'`" -lt "$CRITICAL" ] ; then
echo 'WARNING!!! Disk Space Alert' 

fi

