#!/bin/bash
generateCSV()
{
	#CSV format srNumber,srStatus,MessageType,Status,Time,IPADDRESS,Message
	echo "$1,$2,$3,$4,$5,$6,$7" >> ReportingSystem
}


CURRENT=$(df / | grep / | awk '{ print $5,$6}' | sed 's/%//g')
CRITICAL=90
WARNING=80
DATE=$(date "+%b %_d %H:%M:%S")
ISSUENUMBER=0
REPORTEDFLAG=0

if [ "`echo $CURRENT| awk '{print $1}'`" -gt "$CRITICAL" ] ; then
	echo 'FAIL!!! Disk Space Alert' 
        echo "checking earlier reported incident"
 	CMPLSTR=$(grep `hostname -s` ReportingSystem | grep diskSpace|grep -v 'NA' |tail -1 |grep 'CLOSE'|awk -F',' '{print $1","$2}')
	#DEBUG: echo $CMPLSTR
        #DEBUG: REPORTEDFLAG=1
        REPORTEDFLAG=$(grep `hostname -s` ReportingSystem | grep diskSpace|grep -v 'NA' |tail -1 |grep 'CLOSE'| wc -l )
        #if REPORTEDFLAG is 1, that means last entry for server and message type is CLOSE, then only ADD
        if [ $REPORTEDFLAG == 1 ] ; then
		ISSUENUMBER=$(cat  ReportingSystem |grep -v 'NA' |  awk -F',' '{print $1}' | sort | uniq | tail -1)
		ISSUENUMBER=`expr $ISSUENUMBER + 1`
		generateCSV "$ISSUENUMBER" "NEW" "diskSpace" "FAIL" "$DATE" "`hostname -s`" "Disk Space Alert" 
        fi
#elif [ "`echo $CURRENT| awk '{print $1}'`" -gt "$WARNING" -a "`echo $CURRENT| awk '{print $1}'`" -lt "$CRITICAL" ] ; then
else
	echo 'PASS!!! Disk Space Alert' 
	generateCSV "NA" "NA" "diskSpace" "PASS" "$DATE" "`hostname -s`" "Disk Space Alert"
fi


